<!--///// include:modal__menu-start /////////////////////////////////-->
  <div class="modal modal__menu" style="height:300px; display:none;">
    <div class="modal__content" style="display:none;">
      <a href="javascript: void(0);" class="btn btn--gray btn--w40 mB16" onclick="TokyoAntioch.menuOff()">× 閉じる</a>
      <ul class="modListWhite">
        <li><a href="http://astone-blog.jp/photonews/">最新写真ニュース</a></li>
        <li><a href="/online/">礼拝生中継</a></li>
		<li><a href="/meetings/">礼拝案内・礼拝時間</a></li>
		<li><a href="/s_charisma.html">東京カリスマ聖会・地方のカリスマ聖会</a></li>
		<li><a href="/tlcccsougou/">主の十字架総合サイト</a></li>
		<li><a href="/s_news.html">各集会案内・牧師紹介・伝道師紹介・週報</a></li>
        <li><a href="/s_akashi.html">神の救いと神に
  助けられた体験談</a></li>
        <li><a href="/s_akashi-movie.html">神の救いと神に助けられた体験談(動画)</a></li>
        <li><a href="/movie/201505-antioch/">教会紹介映像</a></li>
        <li><a href="/newlife/">新しい人生に一歩踏み出すために</a></li>
        <li><a href="/movie/201301-26seijin/">日本26聖人の足跡</a></li>
        <li><a href="/blog/">ブログコーナー</a></li>
        <li><a href="http://gospelconcert.jp/">こころごすぺる コンサート</a></li>
        <li><a href="/s_learnings.html">聖書・学び</a></li>
		<li><a href="/link/">リンク</a></li>
      </ul>
    </div>
  </div>
<!--///// include:modal__menu-end /////////////////////////////////-->
