<!--///// include:footer-start /////////////////////////////////-->
    <footer>
      <div class="footer__lower">
        <p><a href="/position/googleanalytics-privacypolicy.html">プライバシーポリシー</a></p>
        東京アンテオケ教会のウエブサイトは<br>
        アストン株式会社が製作しております
      </div>
      <div class="footer__upper bGC_Blu">
        Copyright (C) Tokyo Antioch Church All Rights Reserved.
      </div>
    </footer>
<!--///// include:footer-end /////////////////////////////////-->